version: "3.3"
services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=wephi1234
    volumes:
      - ./data/db:/var/lib/mysql
  nginx:
    image: nginx:alpine
    ports:
      - "8081:80"
    links:
      - "phpfpm"
    volumes:
      - ../src:/var/www/html
      - ./etc/nginx-site.conf:/etc/nginx/conf.d/default.conf
  phpfpm:
    build: ./docker_phpfpm
    links:
      - "db"
    volumes:
      - ../src:/var/www/html

